platform :ios do
  lane :example do
    souyuz(
      platform: "ios",
      build_configuration: "Release",
      plist_path: "./iOS/Info.plist"
    )
  end
end

platform :android do
  lane :example do
    souyuz(
      platform: "android",
      build_configuration: "Release",
      keystore_path: "{PATH_TO_YOUR_KEYSTORE}",
      keystore_alias: "{ALIAS_OF_YOUR_KEYSTORE}",
      keystore_password: "{YOUR_SUPER_SECRET_KEYSTORE_PASSWORD}"
    )
  end
end
